// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200602222727");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1782191464);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1783835136);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1783835016);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1782191584);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1782191494);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1868);
user_pref("browser.cache.disk.capacity", 942080);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1782191434);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7097d547-0ec6-4fc2-9432-566559778895}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1782191480391");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1782193279391");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1782191439635");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1782213039635");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1782191438");
user_pref("browser.slowStartup.averageTime", 4057);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1782191436);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1782191438163");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "6a3b7d81a5a54eb588dd5d26e3d5e969");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"6087dad3-c70a-4cfa-97d9-b1fd1ad0452c\",\"formautofill@mozilla.org\":\"31edf156-e646-4f18-a32d-b7edfdb799f9\",\"screenshots@mozilla.org\":\"09844ec1-545a-446e-9037-3708afd54544\",\"webcompat-reporter@mozilla.org\":\"80d2d1ab-94f1-41d4-99c4-c076ada882d1\",\"webcompat@mozilla.org\":\"8d13d170-26eb-4bbb-8b55-49e9f26b7e4c\",\"default-theme@mozilla.org\":\"54334dd0-19f4-4eb1-809a-6dde6aaa94e9\",\"google@search.mozilla.org\":\"d02f17e2-668b-4035-9f47-bbc238f6df92\",\"amazondotcom@search.mozilla.org\":\"ce99fa3e-7d9f-4a4a-b90a-0a36626bb953\",\"bing@search.mozilla.org\":\"0107383e-6b48-410e-a0da-3fd8c0a307f9\",\"ddg@search.mozilla.org\":\"56b6d389-9d7b-47ca-8651-2e13cdba8e35\",\"ebay@search.mozilla.org\":\"22120b4b-8984-49e5-b657-39b042291195\",\"twitter@search.mozilla.org\":\"1bb10c16-d8ec-48f9-8fdf-744911e7e0e3\",\"wikipedia@search.mozilla.org\":\"9a6d89e1-88f2-4b13-9de4-67109206e029\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1783835109);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1782191469);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200602222727");
user_pref("media.gmp-manager.lastCheck", 1782191468);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1783835109);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "8cdaf4ec-28dd-43dc-a9a8-9066e22612ce");
user_pref("security.sandbox.plugin.tempDirSuffix", "5e0f5c9a-da44-4698-ab7d-d43c9ec4a25b");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1783835109);
user_pref("toolkit.startup.last_success", 1782191431);
user_pref("toolkit.telemetry.cachedClientID", "362e2290-ad82-4b0a-8da2-ad9094806ec7");
user_pref("toolkit.telemetry.previousBuildID", "20200602222727");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
